/*
 * City.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package app.cityscout.model

import java.math.BigDecimal

import javax.annotation.processing.Generated

@Generated
data class City(
    val name: CityName,
    val reason: String,
    val img: String,
    val redfin: String,
    val lat: BigDecimal,
    val lon: BigDecimal,
    val population: Population,
    val weather: Weather
)
