/*
 * CityName.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package app.cityscout.model

import javax.annotation.processing.Generated

@Generated
data class CityName(
    val city: String,
    val state: String,
    val abbr: String,
    val slug: String
)
