/*
 * Population.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package app.cityscout.model

import javax.annotation.processing.Generated
import kotlinx.serialization.Serializable

@Serializable
@Generated
data class Population(
    val total: Long,
    val male: Long,
    val male_under_18: Long,
    val male_18_to_24: Long,
    val male_25_to_30: Long,
    val male_30_to_40: Long,
    val male_40_to_50: Long,
    val male_50_to_60: Long,
    val male_over_60: Long,
    val female: Long,
    val female_under_18: Long,
    val female_18_to_24: Long,
    val female_25_to_30: Long,
    val female_30_to_40: Long,
    val female_40_to_50: Long,
    val female_50_to_60: Long,
    val female_over_60: Long
)
