/*
 * Weather.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package app.cityscout.model

import java.math.BigDecimal

import javax.annotation.processing.Generated

@Generated
data class Weather(
    val days_of_sun: Long,
    val temp_high: BigDecimal,
    val temp_low: BigDecimal,
    val temp_mean: BigDecimal,
    val snow_inches: BigDecimal,
    val rain_inches: BigDecimal,
    val monthly_means: Monthly_means
) {

    data class Monthly_means(
        val month: List<String>,
        val temperature_2m_mean: List<String>,
        val temperature_2m_max: List<String>,
        val temperature_2m_min: List<String>
    )

}
