/*
 * City.ts
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */

import {CityName} from "./CityName";
import {Population} from "./Population";

export interface City {
    name: CityName;
    reason: string;
    img: string;
    redfin?: string;
    population?: Population;
}
