/*
 * MonthlyMeans.ts
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */

export interface MonthlyMeans {
    temperature_2m_mean?: number;
    temperature_2m_max?: number;
    temperature_2m_min?: number;
}
