/*
 * Population.ts
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */

export interface Population {
    total: number;
    male: number;
    male_under_18: number;
    male_18_to_24: number;
    male_25_to_30: number;
    male_30_to_40: number;
    male_40_to_50: number;
    male_50_to_60: number;
    male_over_60: number;
    female: number;
    female_under_18: number;
    female_18_to_24: number;
    female_25_to_30: number;
    female_30_to_40: number;
    female_40_to_50: number;
    female_50_to_60: number;
    female_over_60: number;
}
