/*
 * Weather.ts
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */

export interface Weather {
    days_of_sun: number;
    temp_high: number;
    temp_low: number;
    temp_mean: number;
    snow_inches: number;
    rain_inches: number;
    monthly_means: Monthly_means;
}

export interface Monthly_means {
    month: string[];
    temperature_2m_mean: string[];
    temperature_2m_max: string[];
    temperature_2m_min: string[];
}
